A=/stroke_lib/
all:	$(A)simplex1.ufnt $(A)simplex1_greek.ufnt $(A)duplex1_italic.ufnt \
	$(A)duplex1.ufnt $(A)duplex1_greek.ufnt $(A)duplex_cyrillic.ufnt \
	$(A)duplex_script.ufnt $(A)english_gothic.ufnt $(A)german_gothic.ufnt \
	$(A)italian_gothic.ufnt $(A)map_symbols.ufnt $(A)math_symbols.ufnt \
	$(A)simplex2.ufnt $(A)simplex2_greek.ufnt $(A)triplex_italic.ufnt \
	$(A)triplex_times.ufnt $(A)simplex_script.ufnt $(A)duplex_roman.ufnt

$(A)simplex1.ufnt:	simplex1.fdat fdat_ufnt
	fdat_ufnt simplex1.fdat $(A)simplex1.ufnt 1 0 128
$(A)simplex1_greek.ufnt:	simplex1.fdat fdat_ufnt
	fdat_ufnt simplex1.fdat $(A)simplex1_greek.ufnt 0 128 128
$(A)duplex1_italic.ufnt:	duplex1_italic.fdat fdat_ufnt
	fdat_ufnt duplex1_italic.fdat $(A)duplex1_italic.ufnt 0 0 128
$(A)duplex1.ufnt:	duplex1_times.fdat fdat_ufnt
	fdat_ufnt duplex1_times.fdat $(A)duplex1.ufnt 0 0 128
$(A)duplex1_greek.ufnt:	duplex1_times.fdat fdat_ufnt
	fdat_ufnt duplex1_times.fdat $(A)duplex1_greek.ufnt 0 128 128
$(A)duplex_cyrillic.ufnt:	duplex_cyrillic.fdat fdat_ufnt
	fdat_ufnt duplex_cyrillic.fdat $(A)duplex_cyrillic.ufnt 0 0 128
$(A)duplex_roman.ufnt:	duplex_roman.fdat fdat_ufnt
	fdat_ufnt duplex_roman.fdat $(A)duplex_roman.ufnt 0 0 128
$(A)duplex_script.ufnt:	duplex_script.fdat fdat_ufnt
	fdat_ufnt duplex_script.fdat $(A)duplex_script.ufnt 0 0 128
$(A)english_gothic.ufnt:	english_gothic.fdat fdat_ufnt
	fdat_ufnt english_gothic.fdat $(A)english_gothic.ufnt 0 0 128
$(A)german_gothic.ufnt:	german_gothic.fdat fdat_ufnt
	fdat_ufnt german_gothic.fdat $(A)german_gothic.ufnt 0 0 128
$(A)italian_gothic.ufnt:	italian_gothic.fdat fdat_ufnt
	fdat_ufnt italian_gothic.fdat $(A)italian_gothic.ufnt 0 0 128
$(A)map_symbols.ufnt:	map_symbols.fdat fdat_ufnt
	fdat_ufnt map_symbols.fdat $(A)map_symbols.ufnt 0 0 128
$(A)math_symbols.ufnt:	math_symbols.fdat fdat_ufnt
	fdat_ufnt math_symbols.fdat $(A)math_symbols.ufnt 0 0 128
$(A)simplex2.ufnt:	simplex2.fdat fdat_ufnt
	fdat_ufnt simplex2.fdat $(A)simplex2.ufnt 0 0 128
$(A)simplex2_greek.ufnt:	simplex2_greek.fdat fdat_ufnt
	fdat_ufnt simplex2_greek.fdat $(A)simplex2_greek.ufnt 0 0 128
$(A)simplex_script.ufnt:	simplex_script.fdat fdat_ufnt
	fdat_ufnt simplex_script.fdat $(A)simplex_script.ufnt 0 0 128
$(A)triplex_italic.ufnt:	triplex_italic.fdat fdat_ufnt
	fdat_ufnt triplex_italic.fdat $(A)triplex_italic.ufnt 0 0 128
$(A)triplex_times.ufnt:	triplex_times.fdat fdat_ufnt
	fdat_ufnt triplex_times.fdat $(A)triplex_times.ufnt 0 0 128
